// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoclickController from "./autoclick_controller.js"
application.register("autoclick", AutoclickController)

import SearchController from "./search_controller.js"
application.register("search", SearchController)

import SidebarController from "./sidebar_controller.js"
application.register("sidebar", SidebarController)

import SliderController from "./slider_controller.js"
application.register("slider", SliderController)

import WidgetController from "./widget_controller.js"
application.register("widget", WidgetController)
